### ISSUE TITLE
Implement "None" in course filter

### ISSUE THREAD

**Issue by kaovilai** [iiradia/PackRanks#3]
[gepornot](https://github.com/iiradia/PackRanks/blob/2b902c402d9f18000dac71b2aeda9bbd41755d70/reactjs/frontend/src/components/Home/FirstPrompt.jsx#L32) function need to consider "None" as well
Currently "None" = "Course Department" in _Are you looking for a GEP or a course from a specific department?_

**Comment by iiradia** [comment]
Implemented and deployed, thanks for the suggestion!

**Comment by kaovilai** [comment]
@iiradia I thought "None" meant I am looking for a course but not from a specific department nor does it need to be GEP. "I am just trying to find an easy class to enroll into". Currently "None" = "do nothing".

**Comment by iiradia** [comment]
@kaovilai Interesting, how would users search for a course in that case? Would we just show the easiest courses at NCSU in general?

**Comment by kaovilai** [comment]
Not really for searching in that case. Just for exploring like you said, the easiest classes.
